spring:
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration:

logging:
  level:
    org:
      springframework: WARN
      springframework.security: DEBUG