spring:
  mvc:
    problemdetails:
      enabled: true
  session:
    redis:
      flush-mode: on-save
  docker:
    compose:
      file: docker-compose.dev.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org:
      springframework: ERROR
      springframework.security: DEBUG