spring:
  mvc:
    problemdetails:
      enabled: true
  docker:
    compose:
      file: docker-compose.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  expiration:

logging:
  level:
    org:
      springframework: ERROR
      springframework.security: DEBUG