name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env from secrets
        run: |
            echo DB_URL=${{ secrets.DB_URL }} >> ./backend/.env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> ./backend/.env
            echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> ./backend/.env
            echo DB_NAME=${{ secrets.DB_NAME }} >> ./backend/.env
            echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> ./backend/.env

      - name: Create .env.production from secrets
        run: |
          echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env.production 

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Maven wrapper executable
        working-directory: ./backend
        run: chmod +x mvnw

      - name: Build and Test Backend
        working-directory: ./backend
        run: |
          ./mvnw clean verify
          ./mvnw test

      - name: Backend Code Coverage
        working-directory: ./backend
        run: |
          ./mvnw jacoco:report

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm install --save-dev jest @testing-library/react @testing-library/jest-dom

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  docker-build:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Check if .env file exists
        run: |
          if [ -f ./backend/.env ]; then
            echo ".env file exists"
          else
            echo ".env file not found"
            exit 1
          fi

      - name: Copy .env file to backend
        run: cp ./backend/.env ./backend/.env

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: docker build -t backend-app .

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: docker build -t frontend-app .