name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create backend env file
        run: |
            echo "DB_URL=${DB_URL}" >> .env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
            echo "DB_USERNAME=${DB_USERNAME}" >> .env
            echo "DB_NAME=${DB_NAME}" >> .env
            echo "REDIS_HOST=${REDIS_HOST}" >> .env
            echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Maven wrapper executable
        working-directory: ./backend
        run: chmod +x mvnw

      - name: Build and Test Backend
        working-directory: ./backend
        run: |
          ./mvnw clean verify
          ./mvnw test

      - name: Backend Code Coverage
        working-directory: ./backend
        run: |
          ./mvnw jacoco:report

  frontend-tests:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create frontend env file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> .env

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm install --save-dev jest @testing-library/react @testing-library/jest-dom

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  docker-build:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Create backend env file
        working-directory: ./backend
        run: |
          echo "DB_URL=${DB_URL}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_USERNAME=${DB_USERNAME}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "REDIS_HOST=${REDIS_HOST}" >> .env
          echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> .env

      - name: Create frontend env file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> .env

      - name: Build Backend Docker Image
        working-directory: ./backend
        run: docker build -t backend-app:${{ github.sha }} .

      - name: Build Frontend Docker Image
        working-directory: ./frontend
        run: docker build -t frontend-app:${{ github.sha }} .